repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        types_or: [ html, css ]
        additional_dependencies: [ 'prettier@4.0.0-alpha.8' ]

  - repo: local
    hooks:
      - id: check-html-utf8-meta
        name: Check HTML UTF-8 meta tag
        verbose: true
        entry: |
          bash -c '
          YELLOW="\033[1;33m"
          NC="\033[0m"

          for file in $(find . -name "*.html"); do
            grep -Pzoq "(?s)<head>\s*<meta\s+charset=\"utf-8\"\s*/>" "$file"
            status=$?
            if test $status -eq 1; then
              echo -e "${YELLOW}UTF-8 meta tag not found as first line in <head> in $file${NC}"
            fi
          done

          exit 0
          '
        language: system
        types: [ html ]
        pass_filenames: false

      - id: check-html-inline-styles
        name: Check HTML inline styles
        verbose: true
        entry: |
          bash -c '
          YELLOW="\033[1;33m"
          NC="\033[0m"

          for file in $(find . -name "*.html"); do
            grep -Pnzoq "style=\".*?\"" "$file"
            status=$?
            if test $status -eq 0; then
              echo -e "${YELLOW}Inline style used in $file${NC}"
            fi
          done

          exit 0
          '
        language: system
        types: [ html ]
        pass_filenames: false
